import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Built by JobHunter v2',
  description: 'Per-role landings auto-generated by my agent. The decision was mine.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <style
          dangerouslySetInnerHTML={{
            __html: `
              *, *::before, *::after { box-sizing: border-box; }
              html, body { margin: 0; padding: 0; }
              body {
                font-family: 'Inter', -apple-system, system-ui, sans-serif;
                font-variant-numeric: tabular-nums;
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
                line-height: 1.5;
              }
              ::selection { background: currentColor; color: var(--bg, #FFF); }
              code, .mono { font-family: 'JetBrains Mono', ui-monospace, Menlo, monospace; }
            `,
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
