type Props = {
  job_url: string;
  jd_seen_at: string;
  landing_generated_at: string;
  build_minutes: number;
  source_repo?: string;
  generator_version: string;
  score: number;
  score_breakdown: { label: string; points: number }[];
};

export default function Disclosure(p: Props) {
  return (
    <footer className="section section--surface" style={{ marginTop: 40, fontSize: '0.86rem' }}>
      <p className="eyebrow" style={{ color: 'var(--ink-dim)', marginBottom: 10 }}>Full disclosure — how this landing was made</p>
      <p style={{ marginBottom: 10 }}>
        <strong>This page was generated by my agent.</strong> The decision to apply was mine. The build was the agent's. Every claim is verifiable.
      </p>
      <ul style={{ margin: '8px 0 14px 22px', fontSize: '0.84rem' }}>
        <li>Source JD: <a href={p.job_url} target="_blank" rel="noreferrer">{p.job_url}</a></li>
        <li>JD scored at <code>{p.jd_seen_at}</code> · landing generated at <code>{p.landing_generated_at}</code> · elapsed <strong>{p.build_minutes} min</strong></li>
        <li>Score: <strong>{p.score}/10</strong>{p.score_breakdown.length > 0 && (<>{' ('}{p.score_breakdown.map((b) => `${b.label} ${b.points > 0 ? '+' : ''}${b.points}`).join(' · ')}{')'}</>)}</li>
        <li>Generator: <code>{p.generator_version}</code>{p.source_repo && (<>{' · source: '}<a href={p.source_repo} target="_blank" rel="noreferrer">{p.source_repo}</a></>)}</li>
      </ul>
      <p style={{ fontSize: '0.78rem', color: 'var(--ink-dim)' }}>
        Stack: Next.js (static export) · Vercel · Claude (via Cowork scheduled task) · Greenhouse / Ashby / Lever public job-board APIs · no third-party trackers.
      </p>
    </footer>
  );
}
